# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import test_pb2 as test__pb2


class TestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.rpc = channel.unary_unary(
            "/replit.river.test.Test/rpc",
            request_serializer=test__pb2.RpcRequest.SerializeToString,
            response_deserializer=test__pb2.RpcResponse.FromString,
        )
        self.stream = channel.stream_stream(
            "/replit.river.test.Test/stream",
            request_serializer=test__pb2.StreamRequest.SerializeToString,
            response_deserializer=test__pb2.StreamResponse.FromString,
        )


class TestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def rpc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TestServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "rpc": grpc.unary_unary_rpc_method_handler(
            servicer.rpc,
            request_deserializer=test__pb2.RpcRequest.FromString,
            response_serializer=test__pb2.RpcResponse.SerializeToString,
        ),
        "stream": grpc.stream_stream_rpc_method_handler(
            servicer.stream,
            request_deserializer=test__pb2.StreamRequest.FromString,
            response_serializer=test__pb2.StreamResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "replit.river.test.Test", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Test(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def rpc(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/replit.river.test.Test/rpc",
            test__pb2.RpcRequest.SerializeToString,
            test__pb2.RpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def stream(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/replit.river.test.Test/stream",
            test__pb2.StreamRequest.SerializeToString,
            test__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
