# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ntest.proto\x12\x11replit.river.test"\x1d\n\nRpcMessage\x12\x0f\n\x07payload\x18\x01 \x01(\t"\x83\x03\n\nRpcRequest\x12\x10\n\x06\x64ouble\x18\x01 \x01(\x01H\x00\x12\x0f\n\x05\x66loat\x18\x02 \x01(\x02H\x00\x12\x0f\n\x05int64\x18\x03 \x01(\x03H\x00\x12\x10\n\x06uint64\x18\x04 \x01(\x04H\x00\x12\x0f\n\x05int32\x18\x05 \x01(\x05H\x00\x12\x11\n\x07\x66ixed64\x18\x06 \x01(\x06H\x00\x12\x11\n\x07\x66ixed32\x18\x07 \x01(\x07H\x00\x12\x0e\n\x04\x62ool\x18\x08 \x01(\x08H\x00\x12\x10\n\x06string\x18\t \x01(\tH\x00\x12\x30\n\x07message\x18\x0b \x01(\x0b\x32\x1d.replit.river.test.RpcMessageH\x00\x12\x0f\n\x05\x62ytes\x18\x0c \x01(\x0cH\x00\x12\x10\n\x06uint32\x18\r \x01(\rH\x00\x12*\n\x04\x65num\x18\x0e \x01(\x0e\x32\x1a.replit.river.test.RpcEnumH\x00\x12\x12\n\x08sfixed32\x18\x0f \x01(\x0fH\x00\x12\x12\n\x08sfixed64\x18\x10 \x01(\x10H\x00\x12\x10\n\x06sint32\x18\x11 \x01(\x11H\x00\x12\x10\n\x06sint64\x18\x12 \x01(\x12H\x00\x42\t\n\x07request"\x1e\n\x0bRpcResponse\x12\x0f\n\x07payload\x18\x01 \x01(\t" \n\rStreamRequest\x12\x0f\n\x07payload\x18\x02 \x01(\t"!\n\x0eStreamResponse\x12\x0f\n\x07payload\x18\x02 \x01(\t*%\n\x07RpcEnum\x12\x08\n\x04ZERO\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x32\x9f\x01\n\x04Test\x12\x44\n\x03rpc\x12\x1d.replit.river.test.RpcRequest\x1a\x1e.replit.river.test.RpcResponse\x12Q\n\x06stream\x12 .replit.river.test.StreamRequest\x1a!.replit.river.test.StreamResponse(\x01\x30\x01\x62\x06proto3'  # noqa: E501
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "test_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _globals["_RPCENUM"]._serialized_start = 555
    _globals["_RPCENUM"]._serialized_end = 592
    _globals["_RPCMESSAGE"]._serialized_start = 33
    _globals["_RPCMESSAGE"]._serialized_end = 62
    _globals["_RPCREQUEST"]._serialized_start = 65
    _globals["_RPCREQUEST"]._serialized_end = 452
    _globals["_RPCRESPONSE"]._serialized_start = 454
    _globals["_RPCRESPONSE"]._serialized_end = 484
    _globals["_STREAMREQUEST"]._serialized_start = 486
    _globals["_STREAMREQUEST"]._serialized_end = 518
    _globals["_STREAMRESPONSE"]._serialized_start = 520
    _globals["_STREAMRESPONSE"]._serialized_end = 553
    _globals["_TEST"]._serialized_start = 595
    _globals["_TEST"]._serialized_end = 754
# @@protoc_insertion_point(module_scope)
