# Code generated by river.codegen. DO NOT EDIT.

from pydantic import BaseModel, TypeAdapter


class SetInput(BaseModel):
    k: str
    v: float


SetInputTypeAdapter: TypeAdapter[SetInput] = TypeAdapter(SetInput)


class SetOutput(BaseModel):
    v: int


SetOutputTypeAdapter: TypeAdapter[SetOutput] = TypeAdapter(SetOutput)
