# Code generated by river.codegen. DO NOT EDIT.
from typing import (
    Any,
)

from pydantic import BaseModel, TypeAdapter


class SetInput(BaseModel):
    k: str
    v: float


SetInputTypeAdapter: TypeAdapter[Any] = TypeAdapter(SetInput)


class SetOutput(BaseModel):
    v: int


SetOutputTypeAdapter: TypeAdapter[Any] = TypeAdapter(SetOutput)
