# Code generated by river.codegen. DO NOT EDIT.
from typing import Literal

import replit_river as river
from pydantic import BaseModel  # noqa: F401

from .kv import KvService
from .repeat import RepeatService
from .upload import UploadService


class TestCient:
    def __init__(self, client: river.Client[Literal[None]]):
        self.kv = KvService(client)
        self.repeat = RepeatService(client)
        self.upload = UploadService(client)
