# Code generated by river.codegen. DO NOT EDIT.
import datetime
from collections.abc import AsyncIterable, AsyncIterator  # noqa: F401
from typing import Any

import replit_river as river
from pydantic import TypeAdapter  # noqa: F401
from replit_river.error_schema import RiverError, RiverErrorTypeAdapter

from .set import SetInit, SetInitTypeAdapter, SetOutput, SetOutputTypeAdapter
from .watch import (
    WatchErrors,
    WatchErrorsTypeAdapter,
    WatchInit,
    WatchInitTypeAdapter,
    WatchOutput,
    WatchOutputTypeAdapter,
)


class KvService:
    def __init__(self, client: river.v2.Client[Any]):
        self.client = client

    async def set(
        self,
        init: SetInit,
        timeout: datetime.timedelta,
    ) -> SetOutput:
        return await self.client.send_rpc(
            "kv",
            "set",
            init,
            lambda x: SetInitTypeAdapter.validate_python(x),
            lambda x: SetOutputTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
            lambda x: RiverErrorTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
            timeout,
        )

    async def watch(
        self,
        init: WatchInit,
    ) -> AsyncIterator[WatchOutput | WatchErrors | RiverError]:
        return self.client.send_subscription(
            "kv",
            "watch",
            init,
            lambda x: WatchInitTypeAdapter.validate_python(x),
            lambda x: WatchOutputTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
            lambda x: WatchErrorsTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
        )
