# Code generated by river.codegen. DO NOT EDIT.

from pydantic import BaseModel, TypeAdapter


class SetInit(BaseModel):
    k: str
    v: float


class SetOutput(BaseModel):
    v: int


SetOutputTypeAdapter: TypeAdapter[SetOutput] = TypeAdapter(SetOutput)


SetInitTypeAdapter: TypeAdapter[SetInit] = TypeAdapter(SetInit)
