# Code generated by river.codegen. DO NOT EDIT.

from pydantic import BaseModel, TypeAdapter


class EchoInput(BaseModel):
    str: str


EchoInputTypeAdapter: TypeAdapter[EchoInput] = TypeAdapter(EchoInput)


class EchoOutput(BaseModel):
    out: str


EchoOutputTypeAdapter: TypeAdapter[EchoOutput] = TypeAdapter(EchoOutput)
