# Code generated by river.codegen. DO NOT EDIT.

from pydantic import BaseModel, TypeAdapter


class Echo_PrefixInit(BaseModel):
    prefix: str


class Echo_PrefixInput(BaseModel):
    str: str


Echo_PrefixInputTypeAdapter: TypeAdapter[Echo_PrefixInput] = TypeAdapter(
    Echo_PrefixInput
)


class Echo_PrefixOutput(BaseModel):
    out: str


Echo_PrefixOutputTypeAdapter: TypeAdapter[Echo_PrefixOutput] = TypeAdapter(
    Echo_PrefixOutput
)
