# Code generated by river.codegen. DO NOT EDIT.
from typing import (
    Any,
)

from pydantic import BaseModel, TypeAdapter


class Echo_PrefixInit(BaseModel):
    prefix: str


class Echo_PrefixInput(BaseModel):
    str: str


Echo_PrefixInputTypeAdapter: TypeAdapter[Any] = TypeAdapter(Echo_PrefixInput)


class Echo_PrefixOutput(BaseModel):
    out: str


Echo_PrefixOutputTypeAdapter: TypeAdapter[Any] = TypeAdapter(Echo_PrefixOutput)
