# Code generated by river.codegen. DO NOT EDIT.
from typing import (
    Any,
)

from pydantic import BaseModel, TypeAdapter


class EchoInput(BaseModel):
    str: str


EchoInputTypeAdapter: TypeAdapter[Any] = TypeAdapter(EchoInput)


class EchoOutput(BaseModel):
    out: str


EchoOutputTypeAdapter: TypeAdapter[Any] = TypeAdapter(EchoOutput)
