# Code generated by river.codegen. DO NOT EDIT.

from pydantic import BaseModel, TypeAdapter


class EchoInit(BaseModel):
    pass


class EchoInput(BaseModel):
    str: str


class EchoOutput(BaseModel):
    out: str


EchoOutputTypeAdapter: TypeAdapter[EchoOutput] = TypeAdapter(EchoOutput)


EchoInitTypeAdapter: TypeAdapter[EchoInit] = TypeAdapter(EchoInit)


EchoInputTypeAdapter: TypeAdapter[EchoInput] = TypeAdapter(EchoInput)
