export const HEARTBEAT_MS = 500
export const HEARTBEATS_TO_DEAD = 2
export const SESSION_DISCONNECT_GRACE = 3000

// wait durations
export const GRACE_MS = 250
export const DISCONNECT_PERIOD_MS = HEARTBEATS_TO_DEAD * HEARTBEAT_MS + GRACE_MS 
export const SESSION_DISCONNECT_MS = DISCONNECT_PERIOD_MS + SESSION_DISCONNECT_GRACE