# Code generated by river.codegen. DO NOT EDIT.
from typing import (
    Literal,
)

from pydantic import BaseModel, TypeAdapter


class SendInit(BaseModel):
    pass


SendInputPart = Literal["EOF"] | str


class SendInput(BaseModel):
    part: SendInputPart


class SendOutput(BaseModel):
    doc: str


SendOutputTypeAdapter: TypeAdapter[SendOutput] = TypeAdapter(SendOutput)


SendInitTypeAdapter: TypeAdapter[SendInit] = TypeAdapter(SendInit)


SendInputTypeAdapter: TypeAdapter[SendInput] = TypeAdapter(SendInput)
