# Code generated by river.codegen. DO NOT EDIT.
from typing import (
    Any,
    Literal,
)

from pydantic import BaseModel, TypeAdapter

SendInputPart = Literal["EOF"] | str


class SendInput(BaseModel):
    part: SendInputPart


SendInputTypeAdapter: TypeAdapter[Any] = TypeAdapter(SendInput)


class SendOutput(BaseModel):
    doc: str


SendOutputTypeAdapter: TypeAdapter[Any] = TypeAdapter(SendOutput)
