# Code generated by river.codegen. DO NOT EDIT.
from typing import (
    Literal,
)

from pydantic import BaseModel, TypeAdapter

SendInputPart = Literal["EOF"] | str


class SendInput(BaseModel):
    part: SendInputPart


SendInputTypeAdapter: TypeAdapter[SendInput] = TypeAdapter(SendInput)


class SendOutput(BaseModel):
    doc: str


SendOutputTypeAdapter: TypeAdapter[SendOutput] = TypeAdapter(SendOutput)
