# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x11replit.river.test\"\'\n\tKVRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"\x17\n\nKVResponse\x12\t\n\x01v\x18\x01 \x01(\x05\"\x18\n\tEchoInput\x12\x0b\n\x03str\x18\x01 \x01(\t\"\x19\n\nEchoOutput\x12\x0b\n\x03out\x18\x01 \x01(\t\"\x1b\n\x0bUploadInput\x12\x0c\n\x04part\x18\x01 \x01(\t\"\x1b\n\x0cUploadOutput\x12\x0b\n\x03\x64oc\x18\x01 \x01(\t2\xa4\x02\n\x04Test\x12\x42\n\x03set\x12\x1c.replit.river.test.KVRequest\x1a\x1d.replit.river.test.KVResponse\x12\x46\n\x05watch\x12\x1c.replit.river.test.KVRequest\x1a\x1d.replit.river.test.KVResponse0\x01\x12G\n\x04\x65\x63ho\x12\x1c.replit.river.test.EchoInput\x1a\x1d.replit.river.test.EchoOutput(\x01\x30\x01\x12G\n\x06upload\x12\x1c.replit.river.test.EchoInput\x1a\x1d.replit.river.test.EchoOutput(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KVREQUEST']._serialized_start=36
  _globals['_KVREQUEST']._serialized_end=75
  _globals['_KVRESPONSE']._serialized_start=77
  _globals['_KVRESPONSE']._serialized_end=100
  _globals['_ECHOINPUT']._serialized_start=102
  _globals['_ECHOINPUT']._serialized_end=126
  _globals['_ECHOOUTPUT']._serialized_start=128
  _globals['_ECHOOUTPUT']._serialized_end=153
  _globals['_UPLOADINPUT']._serialized_start=155
  _globals['_UPLOADINPUT']._serialized_end=182
  _globals['_UPLOADOUTPUT']._serialized_start=184
  _globals['_UPLOADOUTPUT']._serialized_end=211
  _globals['_TEST']._serialized_start=214
  _globals['_TEST']._serialized_end=506
# @@protoc_insertion_point(module_scope)
